jokes = [
'A woman gets on a bus with her baby. The bus driver says: \"Ugh, that\'s the ugliest baby I\'ve ever seen!\" The woman walks to the rear of the bus and sits down, fuming. She says to a man next to her: \"The driver just insulted me!\" The man says: \"You go up there and tell him off. Go on, I\'ll hold your monkey for you.\"', 
'\"I went to the zoo the other day, there was only one dog in it, it was a shitzu.\"', 
'\"Dyslexic man walks into a bra\"', 
'A young blonde woman is distraught because she fears her husband is having an affair, so she goes to a gun shop and buys a handgun. The next day she comes home to find her husband in bed with a beautiful redhead. She grabs the gun and holds it to her own head. The husband jumps out of bed, begging and pleading with her not to shoot herself. Hysterically the blonde responds to the husband, \"Shut up...you\'re next!\"', 
'A classic Tommy Cooper gag \"I said to the Gym instructor "Can you teach me to do the splits?\" He said, \"How flexible are you?\" I said, \"I can\'t make Tuesdays\", was fifth.', 
'Police arrested two kids yesterday, one was drinking battery acid, the other was eating fireworks. They charged one - and let the other one off.', 
'Two aerials meet on a roof - fall in love - get married. The ceremony was rubbish - but the reception was brilliant.', 
'Another one was: Doc, I can\'t stop singing the \'Green Green Grass of Home\'. He said: \'That sounds like Tom Jones syndrome\'. \'Is it common?\'I asked. \'It\'s not unusual\' he replied.', 
'I\'m on a whiskey diet. I\'ve lost three days already.', 
'A man walks into a bar with a roll of tarmac under his arm and says: \"Pint please, and one for the road.\"', 
'I went to the doctors the other day and I said, \'Have you got anything for wind?\' So he gave me a kite.', 
'My mother-in-law fell down a wishing well, I was amazed, I never knew they worked.', 
'I saw this bloke chatting up a cheetah; I thought, \"He\'s trying to pull a fast one\".', 
'A woman has twins, and gives them up for adoption. One of them goes to a family in Egypt and is named \'Amal.\' The other goes to a family in Spain, they name him Juan\'. Years later; Juan sends a picture of himself to his mum. Upon receiving the picture, she tells her husband that she wished she also had a picture of Amal. Her husband responds, \"But they are twins. If you\'ve seen Juan, you\'ve seen Amal.\"', 
'There\'s two fish in a tank, and one says \"How do you drive this thing?\"', 
'I went to buy some camouflage trousers the other day but I couldn\'t find any.', 
'When Susan\'s boyfriend proposed marriage to her she said: \"I love the simple things in life, but I don\'t want one of them for my husband\".', 
'\"My therapist says I have a preoccupation with vengeance. We\'ll see about that.\"', 
'I rang up British Telecom, I said, \"I want to report a nuisance caller\", he said \"Not you again\".', 
'I met a Dutch girl with inflatable shoes last week, phoned her up to arrange a date but unfortunately she\'d popped her clogs.', 
'A jump-lead walks into a bar. The barman says \"I\'ll serve you, but don\'t start anything\"', 
'Slept like a log last night........ Woke up in the fireplace.', 
'A priest, a rabbi and a vicar walk into a bar. The barman says, \"Is this some kind of joke?\"', 
'A sandwich walks into a bar. The barman says \"Sorry we don\'t serve food in here\"', 
'The other day I sent my girlfriend a huge pile of snow. I rang her up, I said \"Did you get my drift?\".', 
'I cleaned the attic with the wife the other day. Now I can\'t get the cobwebs out of her hair.', 
'Went to the paper shop - it had blown away.', 
'A group of chess enthusiasts checked into a hotel and were standing in the lobby discussing their recent tournament victories. After about an hour, the manager came out of the office and asked them to disperse. \"But why?\" they asked, as they moved off. \"because,\" he said \"I can\'t stand chess nuts boasting in an open foyer.\"', 
'I was in Tesco\'s and I saw this man and woman wrapped in a barcode. I said, \"Are you two an item?\"', 
'I\'m in great mood tonight because the other day I entered a competition and I won a years supply of Marmite......... one jar.', 
'So I went to the Chinese restaurant and this duck came up to me with a red rose and says \"Your eyes sparkle like diamonds\". I said, \"Waiter, I asked for a-ROMATIC duck\".', 
'Four fonts walk into a bar the barman says \"Oi - get out! We don\'t want your type in here\"', 
'I was having dinner with Garry Kasporov (world chess champion) and there was a check tablecloth. It took him two hours to pass me the salt.', 
'There was a man who entered a local paper\'s pun contest.. He sent in ten different puns, in the hope that at least one of the puns would win. Unfortunately, no pun in ten did.', 
'I went down the local supermarket, I said, \"I want to make a complaint, this vinegar\'s got lumps in it\", he said, "Those are pickled onions\".', 
'I backed a horse last week at ten to one. It came in at quarter past four.', 
'I swear, the other day I bought a packet of peanuts, and on the packet it said \"may contain nuts.\" Well, YES! That\'s what I bought the buggers for! You\'d be annoyed if you opened it and a socket set fell out!\"', 
'A lorry-load of tortoises crashed into a trainload of terrapins, What a turtle disaster', 
'My phone will ring at 2 in the morning, and my wife\'ll look at me and go, \"Who\'s that calling at this time?\' \"I don\'t know! If I knew that we wouldn\'t need the bloody phone!\"', 
'I said to this train driver \"I want to go to Paris". He said \"Eurostar?\" I said, \"I\'ve been on telly but I\'m no Dean Martin\".', 
'Two Eskimos sitting in a kayak were chilly. But when they lit a fire in the craft, it sank, proving once and for all that you can\'t have your kayak and heat it.', 
'I\'ve got a friend who\'s fallen in love with two school bags, he\'s bisatchel.', 
'You see my next-door neighbour worships exhaust pipes, he\'s a catholic converter.', 
'A three-legged dog walks into a saloon in the Old West. He slides up to the bar and announces: \"I\'m looking for the man who shot my paw.\"', 
'I tried water polo but my horse drowned.', 
'I\'ll tell you what I love doing more than anything: trying to pack myself in a small suitcase. I can hardly contain myself.', 
'So I met this gangster who pulls up the back of people\'s pants, it was Wedgie Kray.', 
'Went to the corner shop - bought 4 corners.', 
'A seal walks into a club...', 
'I went to the Doctors the other day, and he said, \'Go to Bournemouth, it\'s great for flu\'. So I went - and I got it.'
]