import datetime

recipients = [
("Oralia@fakemail.com", "Oralia Moriarty"), 
("Donny@fakemail.com", "Donny Wicker"), 
("Rosamaria@fakemail.com", "Rosamaria Cato"), 
("Queen@fakemail.com", "Queen Willard"), 
("Steven@fakemail.com", "Steven Koch"), 
("Rhea@fakemail.com", "Rhea Mccorkle"), 
("Isreal@fakemail.com", "Isreal Talbot"), 
("Nga@fakemail.com", "Nga Halstead"), 
("Dominique@fakemail.com", "Dominique Gerber"), 
("Sharron@fakemail.com", "Sharron Pettis"), 
("Orval@fakemail.com", "Orval Thorton"), 
("Catrina@fakemail.com", "Catrina Hastings"), 
("Fidel@fakemail.com", "Fidel Stahl"), 
("Cherlyn@fakemail.com", "Cherlyn Sykes"), 
("Renaldo@fakemail.com", "Renaldo Stack"), 
("Evia@fakemail.com", "Evia Snipes"), 
("Verline@fakemail.com", "Verline Scanlon"), 
("Adolfo@fakemail.com", "Adolfo Urbina"), 
("Berenice@fakemail.com", "Berenice Sargent"), 
("Marcelino@fakemail.com", "Marcelino Bounds"), 
("Tova@fakemail.com", "Tova Prater"), 
("Candy@fakemail.com", "Candy Earls"), 
("Elnora@fakemail.com", "Elnora Paris"), 
("Roseann@fakemail.com", "Roseann Woodall"), 
("Salome@fakemail.com", "Salome Mcfall"), 
("Raeann@fakemail.com", "Raeann Roper"), 
("Glendora@fakemail.com", "Glendora Derrick"), 
("Liana@fakemail.com", "Liana Demers"), 
("Moriah@fakemail.com", "Moriah Rayford"), 
("Velvet@fakemail.com", "Velvet Paquette"), 
("Carrol@fakemail.com", "Carrol Adler"), 
("Enola@fakemail.com", "Enola Currier"), 
("Gidget@fakemail.com", "Gidget Lombardi"), 
("Edris@fakemail.com", "Edris Larose"), 
("Zenia@fakemail.com", "Zenia Metz"), 
("Else@fakemail.com", "Else Thayer"), 
("Gerald@fakemail.com", "Gerald Kyle"), 
("Remona@fakemail.com", "Remona Callender"), 
("Jerrie@fakemail.com", "Jerrie Penn"), 
("Exie@fakemail.com", "Exie Sommer"), 
("Chanel@fakemail.com", "Chanel Atwood"), 
("Alta@fakemail.com", "Alta Clanton"), 
("Allena@fakemail.com", "Allena Partin"), 
("Jaquelyn@fakemail.com", "Jaquelyn Still"), 
("Lucila@fakemail.com", "Lucila Runyon"), 
("Donita@fakemail.com", "Donita Shively"), 
("Keisha@fakemail.com", "Keisha Durham"), 
("Dewayne@fakemail.com", "Dewayne Tamayo"), 
("Shaneka@fakemail.com", "Shaneka Dodd"), 
("Jeanetta@fakemail.com", "Jeanetta Knowles")]


startDate = datetime.datetime.today()

daycount = datetime.timedelta(5)
