# GCS Google Custom Search URL Builder
# Currently only a few fields are used in the DB due to resource and knowledge constraints
# More can be added later from the template below
# Current GCS JSON Params: https://developers.google.com/custom-search/json-api/v1/reference/cse/list
# Current GCS REST Params: https://developers.google.com/custom-search/json-api/v1/using_rest
"""
JSON Template:
"template":
    "https://www.googleapis.com/customsearch/v1?
    q={searchTerms}
    &num={count?}
    &start={startIndex?}
    &lr={language?}
    &safe={safe?}
    &cx={cx?}
    &cref={cref?}
    &sort={sort?}
    &filter={filter?}
    &gl={gl?}
    &cr={cr?}
    &googlehost={googleHost?}
    &c2coff={disableCnTwTranslation?}
    &hq={hq?}&hl={hl?}
    &siteSearch={siteSearch?}
    &siteSearchFilter={siteSearchFilter?}
    &exactTerms={exactTerms?}
    &excludeTerms={excludeTerms?}
    &linkSite={linkSite?}
    &orTerms={orTerms?}
    &relatedSite={relatedSite?}
    &dateRestrict={dateRestrict?}
    &lowRange={lowRange?}
    &highRange={highRange?}
    &searchType={searchType}
    &fileType={fileType?}
    &rights={rights?}
    &imgSize={imgSize?}
    &imgType={imgType?}
    &imgColorType={imgColorType?}
    &imgDominantColor={imgDominantColor?}
    &alt=json"
"""

from urllib.request import urlopen
import json


class GCSUrlBuilder:
    def __init__(self):
        # IMPORTANT: These component keys MUST match their google template counterparts!!!
        self.urlComponents = {
            'mainUrl': "https://www.googleapis.com/customsearch/v1?"
            , 'q': None
            , 'start': None # This is for the start index of the search, not the save()
            # TODO: For Enums: https://developers.google.com/custom-search/docs/xml_results_appendices
            # lr: Restricts the search to documents written in a particular language
            , 'lr': None # TODO: language enum
            # cr: Restricts search results to documents originating in a particular country.
            , 'cr': None # TODO: country enum # TODO: Add Country To Model
            # gl: Geolocation of end user. Refers to google_gl in model
            , 'gl': None # TODO: Enum here - Pushes preferred countries results up.
            , 'googlehost': None # TODO: Enum here
            # TODO: Pull these fields from DB:
            # SearchEngines in model: search_api
            , 'cx': None # TODO: Pull this from DB - Custom Search ID
            # API Key - api_key in model
            , 'key': None # TODO: Pull this from DB - API Key
            , 'exactTerms': None
            , 'excludeTerms': None
            , 'dateRestrict': None
        }

# TODO: Make sure you account for escape characters in final return

# Probably move all of these values to a database... someday.
# Because of how large these variables are I'm keeping them at the bottom
language_lr = {
    'Arabic': 'lang_ar',
    'Bulgarian': 'lang_bg',
    'Catalan': 'lang_ca',
    'Chinese (Simplified)': 'lang_zh-CN',
    'Chinese (Traditional)': 'lang_zh-TW',
    'Croatian': 'lang_hr',
    'Czech': 'lang_cs',
    'Danish': 'lang_da',
    'Dutch': 'lang_nl',
    'English': 'lang_en',
    'Estonian': 'lang_et',
    'Finnish': 'lang_fi',
    'French': 'lang_fr',
    'German': 'lang_de',
    'Greek': 'lang_el',
    'Hebrew': 'lang_iw',
    'Hungarian': 'lang_hu',
    'Icelandic': 'lang_is',
    'Indonesian': 'lang_id',
    'Italian': 'lang_it',
    'Japanese': 'lang_ja',
    'Korean': 'lang_ko',
    'Latvian': 'lang_lv',
    'Lithuanian': 'lang_lt',
    'Norwegian': 'lang_no',
    'Polish': 'lang_pl',
    'Portuguese': 'lang_pt',
    'Romanian': 'lang_ro',
    'Russian': 'lang_ru',
    'Serbian': 'lang_sr',
    'Slovak': 'lang_sk',
    'Slovenian': 'lang_sl',
    'Spanish': 'lang_es',
    'Swedish': 'lang_sv',
    'Turkish': 'lang_tr',
}

country_cr = {
    'Afghanistan': 'countryAF',
    'Albania': 'countryAL',
    'Algeria': 'countryDZ',
    'American Samoa': 'countryAS',
    'Andorra': 'countryAD',
    'Angola': 'countryAO',
    'Anguilla': 'countryAI',
    'Antarctica': 'countryAQ',
    'Antigua and Barbuda': 'countryAG',
    'Argentina': 'countryAR',
    'Armenia': 'countryAM',
    'Aruba': 'countryAW',
    'Australia': 'countryAU',
    'Austria': 'countryAT',
    'Azerbaijan': 'countryAZ',
    'Bahamas': 'countryBS',
    'Bahrain': 'countryBH',
    'Bangladesh': 'countryBD',
    'Barbados': 'countryBB',
    'Belarus': 'countryBY',
    'Belgium': 'countryBE',
    'Belize': 'countryBZ',
    'Benin': 'countryBJ',
    'Bermuda': 'countryBM',
    'Bhutan': 'countryBT',
    'Bolivia': 'countryBO',
    'Bosnia and Herzegovina': 'countryBA',
    'Botswana': 'countryBW',
    'Bouvet Island': 'countryBV',
    'Brazil': 'countryBR',
    'British Indian Ocean Territory': 'countryIO',
    'Brunei Darussalam': 'countryBN',
    'Bulgaria': 'countryBG',
    'Burkina Faso': 'countryBF',
    'Burundi': 'countryBI',
    'Cambodia': 'countryKH',
    'Cameroon': 'countryCM',
    'Canada': 'countryCA',
    'Cape Verde': 'countryCV',
    'Cayman Islands': 'countryKY',
    'Central African Republic': 'countryCF',
    'Chad': 'countryTD',
    'Chile': 'countryCL',
    'China': 'countryCN',
    'Christmas Island': 'countryCX',
    'Cocos (Keeling) Islands': 'countryCC',
    'Colombia': 'countryCO',
    'Comoros': 'countryKM',
    'Congo': 'countryCG',
    'Congo, the Democratic Republic of the': 'countryCD',
    'Cook Islands': 'countryCK',
    'Costa Rica': 'countryCR',
    'Cote D\'ivoire': 'countryCI',
    'Croatia (Hrvatska)': 'countryHR',
    'Cuba': 'countryCU',
    'Cyprus': 'countryCY',
    'Czech Republic': 'countryCZ',
    'Denmark': 'countryDK',
    'Djibouti': 'countryDJ',
    'Dominica': 'countryDM',
    'Dominican Republic': 'countryDO',
    'East Timor': 'countryTP',
    'Ecuador': 'countryEC',
    'Egypt': 'countryEG',
    'El Salvador': 'countrySV',
    'Equatorial Guinea': 'countryGQ',
    'Eritrea': 'countryER',
    'Estonia': 'countryEE',
    'Ethiopia': 'countryET',
    'European Union': 'countryEU',
    'Falkland Islands (Malvinas)': 'countryFK',
    'Faroe Islands': 'countryFO',
    'Fiji': 'countryFJ',
    'Finland': 'countryFI',
    'France': 'countryFR',
    'France, Metropolitan': 'countryFX',
    'French Guiana': 'countryGF',
    'French Polynesia': 'countryPF',
    'French Southern Territories': 'countryTF',
    'Gabon': 'countryGA',
    'Gambia': 'countryGM',
    'Georgia': 'countryGE',
    'Germany': 'countryDE',
    'Ghana': 'countryGH',
    'Gibraltar': 'countryGI',
    'Greece': 'countryGR',
    'Greenland': 'countryGL',
    'Grenada': 'countryGD',
    'Guadeloupe': 'countryGP',
    'Guam': 'countryGU',
    'Guatemala': 'countryGT',
    'Guinea': 'countryGN',
    'Guinea-Bissau': 'countryGW',
    'Guyana': 'countryGY',
    'Haiti': 'countryHT',
    'Heard Island and Mcdonald Islands': 'countryHM',
    'Holy See (Vatican City State)': 'countryVA',
    'Honduras': 'countryHN',
    'Hong Kong': 'countryHK',
    'Hungary': 'countryHU',
    'Iceland': 'countryIS',
    'India': 'countryIN',
    'Indonesia': 'countryID',
    'Iran, Islamic Republic of': 'countryIR',
    'Iraq': 'countryIQ',
    'Ireland': 'countryIE',
    'Israel': 'countryIL',
    'Italy': 'countryIT',
    'Jamaica': 'countryJM',
    'Japan': 'countryJP',
    'Jordan': 'countryJO',
    'Kazakhstan': 'countryKZ',
    'Kenya': 'countryKE',
    'Kiribati': 'countryKI',
    'Korea, Democratic People\'s Republic of': 'countryKP',
    'Korea, Republic of': 'countryKR',
    'Kuwait': 'countryKW',
    'Kyrgyzstan': 'countryKG',
    'Lao People\'s Democratic Republic': 'countryLA',
    'Latvia': 'countryLV',
    'Lebanon': 'countryLB',
    'Lesotho': 'countryLS',
    'Liberia': 'countryLR',
    'Libyan Arab Jamahiriya': 'countryLY',
    'Liechtenstein': 'countryLI',
    'Lithuania': 'countryLT',
    'Luxembourg': 'countryLU',
    'Macao': 'countryMO',
    'Macedonia, the Former Yugosalv Republic of': 'countryMK',
    'Madagascar': 'countryMG',
    'Malawi': 'countryMW',
    'Malaysia': 'countryMY',
    'Maldives': 'countryMV',
    'Mali': 'countryML',
    'Malta': 'countryMT',
    'Marshall Islands': 'countryMH',
    'Martinique': 'countryMQ',
    'Mauritania': 'countryMR',
    'Mauritius': 'countryMU',
    'Mayotte': 'countryYT',
    'Mexico': 'countryMX',
    'Micronesia, Federated States of': 'countryFM',
    'Moldova, Republic of': 'countryMD',
    'Monaco': 'countryMC',
    'Mongolia': 'countryMN',
    'Montserrat': 'countryMS',
    'Morocco': 'countryMA',
    'Mozambique': 'countryMZ',
    'Myanmar': 'countryMM',
    'Namibia': 'countryNA',
    'Nauru': 'countryNR',
    'Nepal': 'countryNP',
    'Netherlands': 'countryNL',
    'Netherlands Antilles': 'countryAN',
    'New Caledonia': 'countryNC',
    'New Zealand': 'countryNZ',
    'Nicaragua': 'countryNI',
    'Niger': 'countryNE',
    'Nigeria': 'countryNG',
    'Niue': 'countryNU',
    'Norfolk Island': 'countryNF',
    'Northern Mariana Islands': 'countryMP',
    'Norway': 'countryNO',
    'Oman': 'countryOM',
    'Pakistan': 'countryPK',
    'Palau': 'countryPW',
    'Palestinian Territory': 'countryPS',
    'Panama': 'countryPA',
    'Papua New Guinea': 'countryPG',
    'Paraguay': 'countryPY',
    'Peru': 'countryPE',
    'Philippines': 'countryPH',
    'Pitcairn': 'countryPN',
    'Poland': 'countryPL',
    'Portugal': 'countryPT',
    'Puerto Rico': 'countryPR',
    'Qatar': 'countryQA',
    'Reunion': 'countryRE',
    'Romania': 'countryRO',
    'Russian Federation': 'countryRU',
    'Rwanda': 'countryRW',
    'Saint Helena': 'countrySH',
    'Saint Kitts and Nevis': 'countryKN',
    'Saint Lucia': 'countryLC',
    'Saint Pierre and Miquelon': 'countryPM',
    'Saint Vincent and the Grenadines': 'countryVC',
    'Samoa': 'countryWS',
    'San Marino': 'countrySM',
    'Sao Tome and Principe': 'countryST',
    'Saudi Arabia': 'countrySA',
    'Senegal': 'countrySN',
    'Serbia and Montenegro': 'countryCS',
    'Seychelles': 'countrySC',
    'Sierra Leone': 'countrySL',
    'Singapore': 'countrySG',
    'Slovakia': 'countrySK',
    'Slovenia': 'countrySI',
    'Solomon Islands': 'countrySB',
    'Somalia': 'countrySO',
    'South Africa': 'countryZA',
    'South Georgia and the South Sandwich Islands': 'countryGS',
    'Spain': 'countryES',
    'Sri Lanka': 'countryLK',
    'Sudan': 'countrySD',
    'Suriname': 'countrySR',
    'Svalbard and Jan Mayen': 'countrySJ',
    'Swaziland': 'countrySZ',
    'Sweden': 'countrySE',
    'Switzerland': 'countryCH',
    'Syrian Arab Republic': 'countrySY',
    'Taiwan, Province of China': 'countryTW',
    'Tajikistan': 'countryTJ',
    'Tanzania, United Republic of': 'countryTZ',
    'Thailand': 'countryTH',
    'Togo': 'countryTG',
    'Tokelau': 'countryTK',
    'Tonga': 'countryTO',
    'Trinidad and Tobago': 'countryTT',
    'Tunisia': 'countryTN',
    'Turkey': 'countryTR',
    'Turkmenistan': 'countryTM',
    'Turks and Caicos Islands': 'countryTC',
    'Tuvalu': 'countryTV',
    'Uganda': 'countryUG',
    'Ukraine': 'countryUA',
    'United Arab Emirates': 'countryAE',
    'United Kingdom': 'countryUK',
    'United States': 'countryUS',
    'United States Minor Outlying Islands': 'countryUM',
    'Uruguay': 'countryUY',
    'Uzbekistan': 'countryUZ',
    'Vanuatu': 'countryVU',
    'Venezuela': 'countryVE',
    'Vietnam': 'countryVN',
    'Virgin Islands, British': 'countryVG',
    'Virgin Islands, U.S.': 'countryVI',
    'Wallis and Futuna': 'countryWF',
    'Western Sahara': 'countryEH',
    'Yemen': 'countryYE',
    'Yugoslavia': 'countryYU',
    'Zambia': 'countryZM',
    'Zimbabwe': 'countryZW',
}

# TODO: geolocation_gl enum
# TODO: googlehost enum
# TODO: URL Escaping Dict https://developers.google.com/custom-search/docs/xml_results_appendices

geolocation_gl = {
    'Afghanistan': 'af',
    'Albania': 'al',
    'Algeria': 'dz',
    'American Samoa': 'as',
    'Andorra': 'ad',
    'Angola': 'ao',
    'Anguilla': 'ai',
    'Antarctica': 'aq',
    'Antigua and Barbuda': 'ag',
    'Argentina': 'ar',
    'Armenia': 'am',
    'Aruba': 'aw',
    'Australia': 'au',
    'Austria': 'at',
    'Azerbaijan': 'az',
    'Bahamas': 'bs',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Barbados': 'bb',
    'Belarus': 'by',
    'Belgium': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bermuda': 'bm',
    'Bhutan': 'bt',
    'Bolivia': 'bo',
    'Bosnia and Herzegovina': 'ba',
    'Botswana': 'bw',
    'Bouvet Island': 'bv',
    'Brazil': 'br',
    'British Indian Ocean Territory': 'io',
    'Brunei Darussalam': 'bn',
    'Bulgaria': 'bg',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cambodia': 'kh',
    'Cameroon': 'cm',
    'Canada': 'ca',
    'Cape Verde': 'cv',
    'Cayman Islands': 'ky',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Chile': 'cl',
    'China': 'cn',
    'Christmas Island': 'cx',
    'Cocos (Keeling) Islands': 'cc',
    'Colombia': 'co',
    'Comoros': 'km',
    'Congo': 'cg',
    'Congo, the Democratic Republic of the': 'cd',
    'Cook Islands': 'ck',
    'Costa Rica': 'cr',
    'Cote D\'ivoire': 'ci',
    'Croatia': 'hr',
    'Cuba': 'cu',
    'Cyprus': 'cy',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Djibouti': 'dj',
    'Dominica': 'dm',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Equatorial Guinea': 'gq',
    'Eritrea': 'er',
    'Estonia': 'ee',
    'Ethiopia': 'et',
    'Falkland Islands (Malvinas)': 'fk',
    'Faroe Islands': 'fo',
    'Fiji': 'fj',
    'Finland': 'fi',
    'France': 'fr',
    'French Guiana': 'gf',
    'French Polynesia': 'pf',
    'French Southern Territories': 'tf',
    'Gabon': 'ga',
    'Gambia': 'gm',
    'Georgia': 'ge',
    'Germany': 'de',
    'Ghana': 'gh',
    'Gibraltar': 'gi',
    'Greece': 'gr',
    'Greenland': 'gl',
    'Grenada': 'gd',
    'Guadeloupe': 'gp',
    'Guam': 'gu',
    'Guatemala': 'gt',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Guyana': 'gy',
    'Haiti': 'ht',
    'Heard Island and Mcdonald Islands': 'hm',
    'Holy See (Vatican City State)': 'va',
    'Honduras': 'hn',
    'Hong Kong': 'hk',
    'Hungary': 'hu',
    'Iceland': 'is',
    'India': 'in',
    'Indonesia': 'id',
    'Iran, Islamic Republic of': 'ir',
    'Iraq': 'iq',
    'Ireland': 'ie',
    'Israel': 'il',
    'Italy': 'it',
    'Jamaica': 'jm',
    'Japan': 'jp',
    'Jordan': 'jo',
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kiribati': 'ki',
    'Korea, Democratic People\'s Republic of': 'kp',
    'Korea, Republic of': 'kr',
    'Kuwait': 'kw',
    'Kyrgyzstan': 'kg',
    'Lao People\'s Democratic Republic': 'la',
    'Latvia': 'lv',
    'Lebanon': 'lb',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libyan Arab Jamahiriya': 'ly',
    'Liechtenstein': 'li',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Macao': 'mo',
    'Macedonia, the Former Yugosalv Republic of': 'mk',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Malaysia': 'my',
    'Maldives': 'mv',
    'Mali': 'ml',
    'Malta': 'mt',
    'Marshall Islands': 'mh',
    'Martinique': 'mq',
    'Mauritania': 'mr',
    'Mauritius': 'mu',
    'Mayotte': 'yt',
    'Mexico': 'mx',
    'Micronesia, Federated States of': 'fm',
    'Moldova, Republic of': 'md',
    'Monaco': 'mc',
    'Mongolia': 'mn',
    'Montserrat': 'ms',
    'Morocco': 'ma',
    'Mozambique': 'mz',
    'Myanmar': 'mm',
    'Namibia': 'na',
    'Nauru': 'nr',
    'Nepal': 'np',
    'Netherlands': 'nl',
    'Netherlands Antilles': 'an',
    'New Caledonia': 'nc',
    'New Zealand': 'nz',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Niue': 'nu',
    'Norfolk Island': 'nf',
    'Northern Mariana Islands': 'mp',
    'Norway': 'no',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Palau': 'pw',
    'Palestinian Territory, Occupied': 'ps',
    'Panama': 'pa',
    'Papua New Guinea': 'pg',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Pitcairn': 'pn',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Puerto Rico': 'pr',
    'Qatar': 'qa',
    'Reunion': 're',
    'Romania': 'ro',
    'Russian Federation': 'ru',
    'Rwanda': 'rw',
    'Saint Helena': 'sh',
    'Saint Kitts and Nevis': 'kn',
    'Saint Lucia': 'lc',
    'Saint Pierre and Miquelon': 'pm',
    'Saint Vincent and the Grenadines': 'vc',
    'Samoa': 'ws',
    'San Marino': 'sm',
    'Sao Tome and Principe': 'st',
    'Saudi Arabia': 'sa',
    'Senegal': 'sn',
    'Serbia and Montenegro': 'cs',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Singapore': 'sg',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Solomon Islands': 'sb',
    'Somalia': 'so',
    'South Africa': 'za',
    'South Georgia and the South Sandwich Islands': 'gs',
    'Spain': 'es',
    'Sri Lanka': 'lk',
    'Sudan': 'sd',
    'Suriname': 'sr',
    'Svalbard and Jan Mayen': 'sj',
    'Swaziland': 'sz',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Syrian Arab Republic': 'sy',
    'Taiwan, Province of China': 'tw',
    'Tajikistan': 'tj',
    'Tanzania, United Republic of': 'tz',
    'Thailand': 'th',
    'Timor-Leste': 'tl',
    'Togo': 'tg',
    'Tokelau': 'tk',
    'Tonga': 'to',
    'Trinidad and Tobago': 'tt',
    'Tunisia': 'tn',
    'Turkey': 'tr',
    'Turkmenistan': 'tm',
    'Turks and Caicos Islands': 'tc',
    'Tuvalu': 'tv',
    'Uganda': 'ug',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'uk',
    'United States': 'us',
    'United States Minor Outlying Islands': 'um',
    'Uruguay': 'uy',
    'Uzbekistan': 'uz',
    'Vanuatu': 'vu',
    'Venezuela': 've',
    'Viet Nam': 'vn',
    'Virgin Islands, British': 'vg',
    'Virgin Islands, U.S.': 'vi',
    'Wallis and Futuna': 'wf',
    'Western Sahara': 'eh',
    'Yemen': 'ye',
    'Zambia': 'zm',
    'Zimbabwe': 'zw',
}